services:
  db:
    image: postgres:17
    container_name: total_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./backend:/app
  #   working_dir: /app

  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    volumes:
      - frontend-dist:/app/dist
    working_dir: /app

  # admin:
  #   build:
  #     context: ./admin
  #     dockerfile: Dockerfile
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./admin:/app
  #   working_dir: /app
  #   command: ./start.sh

  nginx:
    image: nginx:alpine
    container_name: total_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend-dist:/usr/share/nginx/html:ro
      - ${SSL_CERT_PATH}:/etc/ssl/fullchain.pem:ro
      - ${SSL_KEY_PATH}:/etc/ssl/privkey.pem:ro
    env_file:
      - .env
    depends_on:
      # - backend
      - frontend-builder
      # - admin

volumes:
  postgres_data:
  frontend-dist: